framework:
    messenger:
        default_bus: messenger.bus.commands

        buses:
            messenger.bus.commands:
                middleware:
                    - validation
                    - handle_message_in_new_transaction
                    - doctrine_transaction
            messenger.bus.events:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
                    - handle_message_in_new_transaction
                    - doctrine_transaction
